name: Bug
description: Report a defect
title: "Bug: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: What is happening?
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1.
        2.
        3.
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should happen?
    validations:
      required: false