name: User Story
description: Sprint-sized deliverable under a Feature
title: "Story: "
labels: ["story"]
body:
  - type: input
    id: parent-feature
    attributes:
      label: Parent Feature
      description: Enter the Feature issue number
      placeholder: "#feature-issue-number"
    validations:
      required: true

  - type: textarea
    id: story
    attributes:
      label: User Story
      placeholder: |
        As a <user>
        I want <goal>
        So that <benefit>
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - Given ...
        - When ...
        - Then ...
    validations:
      required: true

  - type: input
    id: estimate
    attributes:
      label: Story Points
      placeholder: 1, 2, 3, 5, 8
    validations:
      required: true