name: Task
description: Technical implementation under a Story
title: "Task: "
labels: ["task"]
body:

  - type: textarea
    id: description
    attributes:
      label: Task Description
      placeholder: Describe the technical work required.
    validations:
      required: true